### PR TITLE
Optional link to web folder

### PR DESCRIPTION
**Pull request by paulkf**

### CODE REVIEW

**Comment by j-d** [comment]
I think we said that it would be the same as the project name....

**Comment by paulkf** [comment]
This links the web root to the web folder to ensure you do not need to add /web

**Comment by paulkf** [comment]
It is optional

**Comment by j-d** [comment]
When do you add web ?

**Comment by paulkf** [comment]
The web is added in the site.pp which I added to recruitment

**Comment by paulkf** [comment]
Which is optional, it does not need to be added, if it isnt added it will use the specified we root of /var/www/

I have also tested to ensure phpmyadmin still works

**Pull request merged**
